### ISSUE TITLE
Is writing code after including a template partial a good idea?

### ISSUE THREAD

**Issue by maxmastalerz** [atufkas/yanexbo#1]
This is in reference to the include layout line you put in your views files. Include layout is a regular html document and you are putting content after it. This means you are putting content after the </body></html> tags. I noticed that this content is magically teleported back into the body. I posted a question on this topic here: http://stackoverflow.com/questions/31886017/is-it-bad-practice-to-put-elements-below-the-body-html-tags/31886527#31886527

It appears that this method you are using 'may' not be widely supported by all browsers. I was wondering if it is okay to rely on it working.

I'm not saying your boilerplate is bad, because I like it. I'm just wondering about that one specific section of code and why you rely on it. It does have advantages(I note these in the SO question).

**Comment by atufkas** [comment]
Hi @meaniostack, you're obviously confusing some aspects of _template engines_ and _HTML markup_. Jade (.jade files) is – like the most template languages – pre-processed, i.e. parsed and then translated into HTML. It is designed to ease handling of abstraction, accumulation and substitution of layouts, partials and elements used several times with probably small changes in some details. Of course that is what you want: DRY, define once, use over and over again. The file _index.jade_ you're referring to makes use of the Jade _extends_ keyword allowing us to define a basic layout file, _layout.jade_ in this case, which can hold _block_ definitions (among other keywords) which may be substituted later on by the inheriting file like shown in _index.jade_ where the _block content_ is defined. See the [jade documentation on inheritance](http://jade-lang.com/reference/inheritance/) for details.

**Comment by atufkas** [comment]
As stated above.
